# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.3
  joint_a2: -2
  joint_a3: -2.8
  joint_a4: 1.38
  joint_a5: 0
  joint_a6: 0.827
  joint_a7: -2.88

